export async function searchWithPerplexity(apiKey: string, prompt: string, isDeepResearch: boolean = false) {
  const res = await fetch('https://api.perplexity.ai/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey.trim()}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model: isDeepResearch ? 'sonar-pro' : 'sonar',
      messages: [
        { role: 'system', content: 'You are a search assistant. Provide detailed, factual information to answer the user query. If the query requires deep research, pull as many sources as necessary to provide a comprehensive answer.' },
        { role: 'user', content: prompt }
      ]
    })
  });

  if (!res.ok) {
    const errorData = await res.json().catch(() => ({}));
    throw new Error(errorData.error?.message || `Perplexity API error: ${res.status}`);
  }

  return res.json();
}

export async function searchWithTavily(apiKey: string, prompt: string, isDeepResearch: boolean = false) {
  const res = await fetch('https://api.tavily.com/search', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      api_key: apiKey.trim(),
      query: prompt,
      search_depth: isDeepResearch ? 'advanced' : 'basic',
      include_answer: true,
      include_raw_content: false,
      max_results: isDeepResearch ? 10 : 5
    })
  });

  if (!res.ok) {
    const errorData = await res.json().catch(() => ({}));
    throw new Error(errorData.error || `Tavily API error: ${res.status}`);
  }

  const data = await res.json();

  // Format Tavily results to match our needs
  const citations = data.results.map((r: any) => r.url);
  let content = data.answer ? `Summary: ${data.answer}\n\n` : '';
  content += data.results.map((r: any, i: number) => `[${i + 1}] ${r.title}\n${r.content}`).join('\n\n');

  return { content, citations };
}

export async function synthesizeWithOpenRouter(
  apiKey: string,
  model: string,
  messages: { role: 'user' | 'assistant' | 'system', content: string, attachments?: any[] }[],
  searchResults: string,
  systemPrompt: string,
  onChunk: (text: string) => void,
  signal?: AbortSignal
) {
  const defaultSystemPrompt = "You are an independent, helpful expert assistant. Answer the user's query using the provided search results. The search results contain citation numbers like [1], [2]. You MUST include these citations in your response to indicate where the information came from. IMPORTANT: The search results were generated by another AI. Do NOT adopt its persona. Answer in your own voice. Be comprehensive, clear, and format your response in Markdown.";

  const finalSystemPrompt = systemPrompt.trim() || defaultSystemPrompt;

  // Format messages to include attachments
  const formattedMessages = messages.map(msg => {
    if (msg.attachments && msg.attachments.length > 0) {
      const contentParts: any[] = [{ type: "text", text: msg.content }];
      for (const att of msg.attachments) {
        if (att.isText) {
          contentParts[0].text += `\n\n--- File: ${att.name} ---\n${att.data}`;
        } else {
          contentParts.push({
            type: "image_url",
            image_url: { url: att.data }
          });
        }
      }
      return { role: msg.role, content: contentParts };
    }
    return { role: msg.role, content: msg.content };
  });

  // Append search results to the last user message
  if (searchResults && formattedMessages.length > 0) {
    const lastMessage = formattedMessages[formattedMessages.length - 1];
    if (lastMessage.role === 'user') {
      if (typeof lastMessage.content === 'string') {
        lastMessage.content = `User Query: ${lastMessage.content}\n\nSearch Results Context:\n${searchResults}`;
      } else if (Array.isArray(lastMessage.content)) {
        const textPart = lastMessage.content.find((p: any) => p.type === 'text');
        if (textPart) {
          textPart.text = `User Query: ${textPart.text}\n\nSearch Results Context:\n${searchResults}`;
        }
      }
    }
  }

  const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey.trim()}`,
      'Content-Type': 'application/json',
      'HTTP-Referer': window.location.origin === 'http://localhost' ? 'https://researchai.app' : window.location.origin,
      'X-Title': 'Mac AI Search'
    },
    body: JSON.stringify({
      model: model,
      messages: [
        { role: 'system', content: finalSystemPrompt },
        ...formattedMessages
      ],
      stream: true
    }),
    signal
  });

  if (!res.ok) {
    const errorData = await res.json().catch(() => ({}));
    throw new Error(errorData.error?.message || `OpenRouter API error: ${res.status}`);
  }

  const reader = res.body?.getReader();
  if (!reader) throw new Error('No reader available');

  const decoder = new TextDecoder();
  let done = false;

  while (!done) {
    const { value, done: doneReading } = await reader.read();
    done = doneReading;
    if (value) {
      const chunkValue = decoder.decode(value, { stream: true });
      const lines = chunkValue.split('\n').filter(line => line.trim() !== '');
      for (const line of lines) {
        if (line.startsWith('data: ') && line !== 'data: [DONE]') {
          try {
            const data = JSON.parse(line.slice(6));
            if (data.choices && data.choices[0].delta && data.choices[0].delta.content) {
              onChunk(data.choices[0].delta.content);
            }
          } catch (e) {
            // Ignore parse errors for incomplete chunks
          }
        }
      }
    }
  }
}

export async function generateRelatedQuestions(
  apiKey: string,
  model: string,
  messages: { role: 'user' | 'assistant' | 'system', content: string }[],
  lastResponse: string
) {
  const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey.trim()}`,
      'Content-Type': 'application/json',
      'HTTP-Referer': window.location.origin === 'http://localhost' ? 'https://researchai.app' : window.location.origin,
      'X-Title': 'Mac AI Search'
    },
    body: JSON.stringify({
      model: model,
      messages: [
        {
          role: 'system',
          content: 'Based on the user query and the last assistant response, generate 3 follow-up questions that are short, relevant, and help the user explore the topic deeper. Return only a JSON array of 3 strings. Example: ["How does X affect Y?", "What are the alternatives to Z?", "Tell me more about the history of A."]'
        },
        ...messages.slice(-4),
        { role: 'assistant', content: lastResponse }
      ],
      response_format: { type: "json_object" }
    })
  });

  if (!res.ok) return [];

  try {
    const data = await res.json();
    const content = data.choices[0].message.content;
    const parsed = JSON.parse(content);
    return Array.isArray(parsed) ? parsed : Object.values(parsed).find(v => Array.isArray(v)) || [];
  } catch (e) {
    return [];
  }
}
